

  Connection
    #find()
      âœ“ respond with matching records

  Connection (save error)
    #find()
      1) "before each" hook for "respond with matching records"


  1 passing (18ms)
  1 failing

  1) Connection (save error)
       #find()
         "before each" hook for "respond with matching records":
     Error: Save error
      at Suite.<anonymous> (test/fixtures/asynchronous-hooks.test.js:56:18)
      at Object.<anonymous> (test/fixtures/asynchronous-hooks.test.js:50:1)
      at Module._compile (internal/modules/cjs/loader.js:936:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
      at Module.load (internal/modules/cjs/loader.js:790:32)
      at Function.Module._load (internal/modules/cjs/loader.js:703:12)
      at Module.require (internal/modules/cjs/loader.js:830:19)
      at require (internal/modules/cjs/helpers.js:68:18)
      at Array.forEach (<anonymous>)
      at Module._compile (internal/modules/cjs/loader.js:936:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
      at Module.load (internal/modules/cjs/loader.js:790:32)
      at Function.Module._load (internal/modules/cjs/loader.js:703:12)
      at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
      at /Users/ryusi/.nodebrew/node/v12.10.0/lib/node_modules/npm/node_modules/libnpx/index.js:268:14



